var gulp = require('gulp');
var uglify = require('gulp-uglify');

// Task for minify files generated by Angular
gulp.task('minifyBundles', function () {
  gulp.src(['./dist/polyfills.bundle.js', './dist/main.bundle.js', './dist/styles.bundle.js', './dist/scripts.bundle.js', './dist/vendor.bundle.js',
      './dist/inline.bundle.js','./dist/*.chunk.js'
    ])
    .pipe(uglify())
    .pipe(gulp.dest('./dist/'));
});
gulp.task('default', ['minifyBundles'], function () {});


/* var gulp = require('gulp');
var print = require('gulp-print');

gulp.task('message', function() {
  return gulp.src('package.json')
    .pipe(print(function() { return 'HTTP Server Started'; }));
}); */