/* var gulp = require('gulp');
var uglify = require('gulp-uglify');

// Task for minify files generated by Angular
gulp.task('minifyBundles', function () {
  gulp.src(['./dist/Angular-Lazy-Loading/polyfills.bundle.js', './dist/Angular-Lazy-Loading/main.bundle.js', './dist/Angular-Lazy-Loading/styles.bundle.js', './dist/Angular-Lazy-Loading/scripts.bundle.js', './dist/Angular-Lazy-Loading/vendor.bundle.js','./dist/Angular-Lazy-Loading/runtime.bundle.js','./dist/Angular-Lazy-Loading/*.chunk.js'])
    .pipe(uglify())
    .pipe(gulp.dest('./dist/Angular-Lazy-Loading'));
});
gulp.task('default', ['minifyBundles'], function () {});
 */

var gulp = require('gulp');

gulp.task('default', function() {
  // place code for your default task here
});